file1=open("testfile1.txt","w+")
file1.write("This is my first file")
file1.close()
file2=open("testfile2.txt","w+")
file2.write("This is my second file")
print(file2.tell())
file2.seek(10)
file2.read()
file2.close()

